# Generated by Django 5.0.7 on 2024-12-02 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('director', models.CharField(max_length=20)),
                ('genre', models.CharField(max_length=10)),
                ('content', models.CharField(max_length=550)),
                ('total', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
            options={
                'verbose_name': '영화',
            },
        ),
    ]
